version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pakomi-frontend
    ports:
      - "3000:80"
    networks:
      - pakomi-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pakomi-backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - pakomi-network
    environment:
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@db:3306/${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: pakomi-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pakomi-db-data:/var/lib/mysql
    networks:
      - pakomi-network

networks:
  pakomi-network:
    driver: bridge

volumes:
  pakomi-db-data:
    driver: local
